name: dart_esr
description: dart-esr is a dart package used to generate an EOSIO signing request (ESR) to be send to a wallet (Anchor) to be sign
version: 0.1.0
homepage: https://github.com/EOS-Nation/dart-esr

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.0+4
  json_annotation: ^3.0.1
  pointycastle: ^1.0.2
    
dev_dependencies:
  test: ^1.0.0
  build_runner: ^1.7.4
