name: dart_esr
description: Dart package to encode/decode EOSIO Signing Request
version: 0.0.1
homepage: https://github.com/EOS-Nation/dart-esr

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.0+4
  json_annotation: ^3.0.1
  pointycastle: ^1.0.2
    
dev_dependencies:
  test: ^1.0.0
  build_runner: ^1.7.4
